[package]
name = "pours"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cp = { path = "../cp" }
petgraph = "0.6.0"
